{
 "title": "Data VIsulation DashBoard",
 "description": "Data VIsulation Using Grafana  Dashboard",
 "time": { "from": "2024-07-02T22:55:37.642Z", "to": "2024-07-03T10:55:37.642Z" },
 "templating": {
  "list": [
   { "name": "table", "label": "table" }
  ]
 },
 "panels": [
  {
   "title": "Total customers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT COUNT(DISTINCT Customer_Id) AS Total_Customers\r\nFROM dataecom_deepak_dev_mca22_du_fd126d99;\r\n-- FROM `${table}`;\r\n"
    }
   ]
  },
  {
   "title": "Total_Revenue",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT SUM(Sales) AS Total_Revenue\r\nFROM dataecom_deepak_dev_mca22_du_fd126d99;\r\n-- FROM `${table}`;\r\n"
    }
   ]
  },
  {
   "title": "Real_Shipping_Days",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT AVG(Days_for_shipping_real) AS Real_Shipping_Days\r\n-- FROM `${table}`;\r\nFROM dataecom_deepak_dev_mca22_du_fd126d99;\r\n"
    }
   ]
  },
  {
   "title": "Scheduled_Shipping_Days",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT \r\nAvg(Days_for_shipment_scheduled) as Scheduled_Shipping_Days\r\n-- FROM `${table}`\r\nFROM dataecom_deepak_dev_mca22_du_fd126d99;"
    }
   ]
  },
  {
   "title": "Payment Method Usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "select Type, count(*) \r\n-- from `${table}`\r\nFROM dataecom_deepak_dev_mca22_du_fd126d99\r\ngroup by Type;"
    }
   ]
  },
  {
   "title": "Customer satisfaction Ratings on orders",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT \r\n    `Delivery_Status`,\r\n    COUNT(*) AS order_count,\r\n    CASE \r\n        WHEN `Delivery_Status` = 'Advance shipping' THEN 'Excellent'\r\n        WHEN `Delivery_Status` = 'Shipping on time' THEN 'Normal'\r\n        WHEN `Delivery_Status` = 'Late delivery' THEN 'Bad'\r\n        WHEN `Delivery_Status` = 'Shipping canceled' THEN 'Neutral'\r\n        ELSE 'No data'\r\n    END AS satisfaction_level\r\n-- FROM \r\n--     `${table}`\r\nFROM dataecom_deepak_dev_mca22_du_fd126d99\r\nGROUP BY \r\n    `Delivery_Status`;\r\n\r\n"
    }
   ]
  },
  {
   "title": "Cities with having order greater than 1000",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT `Order_City`,\r\n       COUNT(*) AS `order_count`\r\n-- FROM `${table}`\r\nFROM dataecom_deepak_dev_mca22_du_fd126d99\r\nGROUP BY `Order_City`\r\nHAVING `order_count` >= 10;\r\n\r\n"
    }
   ]
  },
  {
   "title": "Average Spendings of Customer in Each Regions",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT Order_Region,Avg(Sales_per_customer)\r\n--  from `${table}`\r\nFROM dataecom_deepak_dev_mca22_du_fd126d99\r\ngroup by Order_Region"
    }
   ]
  },
  {
   "title": "Popular Product with their frequency",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT Product_Name, Count(Product_Name)\r\n-- from `${table}`\r\nFROM dataecom_deepak_dev_mca22_du_fd126d99\r\ngroup by Product_Name\r\nhaving count(Product_Name) >= 100"
    }
   ]
  },
  {
   "title": "Average benefit per order for different Regions",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT avg(Benefit_per_order),Order_Region \r\nFROM dataecom_deepak_dev_mca22_du_fd126d99\r\ngroup by Order_Region;"
    }
   ]
  },
  {
   "title": "Profit Margin for different product categories",
   "type": "table",
   "description": "Profit Margin = Profit/Sales * 100",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT `Category_Name`, \r\n       (`Order_Profit_Per_Order` / `Sales` * 100) AS `Profit_Margin`\r\nFROM dataecom_deepak_dev_mca22_du_fd126d99;\r\n"
    }
   ]
  },
  {
   "title": "Shipping Performances across different regions",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT Order_Region, Avg(Days_for_shipping_real) \r\nFROM dataecom_deepak_dev_mca22_du_fd126d99\r\ngroup by Order_Region;"
    }
   ]
  },
  {
   "title": "Relationship Between Shipping and Sales",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT `Days_for_shipping_real`, SUM(`Sales`) \r\nFROM dataecom_deepak_dev_mca22_du_fd126d99\r\nGROUP BY `Days_for_shipping_real`\r\nORDER BY `Days_for_shipping_real` ASC;\r\n"
    }
   ]
  },
  {
   "title": "Impact of discounts on order values",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT \r\n    CASE \r\n        WHEN Order_Item_Discount >= 0 AND Order_Item_Discount < 0.1 THEN '0%-10%' \r\n        WHEN Order_Item_Discount >= 0.1 AND Order_Item_Discount < 0.2 THEN '10%-20%' \r\n        WHEN Order_Item_Discount >= 0.2 AND Order_Item_Discount < 0.3 THEN '20%-30%' \r\n        WHEN Order_Item_Discount >= 0.3 AND Order_Item_Discount < 0.4 THEN '30%-40%' \r\n        WHEN Order_Item_Discount >= 0.4 AND Order_Item_Discount < 0.5 THEN '40%-50%' \r\n        ELSE '50%+' \r\n    END AS discount_range,\r\n    COUNT(*) AS order_count\r\nFROM dataecom_deepak_dev_mca22_du_fd126d99\r\nGROUP BY \r\n    discount_range;\r\n"
    }
   ]
  },
  {
   "title": "Total sales for each customer segment.",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT Customer_Segment,Sum(Sales)\r\nFROM dataecom_deepak_dev_mca22_du_fd126d99\r\ngroup by Customer_Segment"
    }
   ]
  },
  {
   "title": "Top 5 Cities by Average Order Value",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT \r\n    Customer_City,\r\n    AVG(Order_Item_Quantity) AS average_order_value\r\nFROM dataecom_deepak_dev_mca22_du_fd126d99\r\n--    `nighwantech`.`project_yabhi8990_5`\r\nGROUP BY \r\n    Customer_City\r\nORDER BY \r\n    average_order_value DESC\r\nLIMIT 5;\r\n"
    }
   ]
  },
  {
   "title": "Sales Distribution Across Different Markets",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT Market, Sum(Sales) \r\nFROM dataecom_deepak_dev_mca22_du_fd126d99\r\ngroup by Market;"
    }
   ]
  },
  {
   "title": "Find out the regional product preferences",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": " SELECT \r\n    Order_Region,\r\n    Category_Name,\r\n    COUNT(Order_Id) AS order_count\r\nFROM dataecom_deepak_dev_mca22_du_fd126d99\r\nGROUP BY \r\n    Order_Region,\r\n    Category_Name\r\nORDER BY \r\n    order_count DESC\r\nLimit 20;\r\n\r\n \r\n "
    }
   ]
  }
 ]
}